export SoundForm		from './SoundForm'
export Foot 		from './Foot'
export IntroPrev 	from './IntroPrev'
export SoundBox 	from './SoundBox'
export Left 		from './Left'
export Center 		from './Center'
export Right 		from './Right'