imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@OPUserBundle/Resources/config/services.yml"}
    - { resource: fos_elastica.yml }
    - { resource: oneup_uploader.yml }
    - { resource: framework.yml }
    - { resource: twig.yml }
#    - { resource: assetic.yml }
    - { resource: swiftmailer.yml }
    - { resource: monolog.yml }
    - { resource: jms_serializer.yml }
    - { resource: fos_rest.yml }
    - { resource: nelmio_api_doc.yml }
    - { resource: nelmio_cors.yml }
    - { resource: op_user.yml }
    - { resource: fos_user.yml }
    - { resource: snc_redis.yml }
    - { resource: lsw_memcache.yml }
    - { resource: liip_imagine.yml }
    - { resource: limenius_react.yml }
    - { resource: gos_web_socket.yml }
    - { resource: fos_js_routing.yml }
    - { resource: doctrine_mongodb.yml }
    - { resource: gos_pubsub_router.yml }
    - { resource: sensio_framework_extra.yml }
    - { resource: white_october_pagerfanta.yml }