limenius_react:
    # Other options are "server_side" and "client_side"
    default_rendering: "both"
    
    serverside_rendering:
        # In case of error in server-side rendering, throw exception
        fail_loud: false
        
        # Replay every console.log message produced during server-side rendering
        # in the JavaScript console
        # Note that if enabled it will throw a (harmless) React warning
        trace: true
        
        # Mode can be `"phpexecjs"` (to execute Js from PHP using PhpExecJs),
        # or `"external"` (to rely on an external_server node.js server)
        # Default is `"phpexecjs"`
        mode: "external_server"
        
        # Location of the server bundle, that contains React and React on Rails.
        # null will default to `%kernel.root_dir%/Resources/webpack/server-bundle.js`
        # Only used with mode `phpexecjs`
        server_bundle_path: null
        
        # Only used with mode `external`
        # Location of the socket to communicate with a dummy node.js server. 
        # Socket type must be acceptable by php function stream_socket_client. Example unix://node.sock, tcp://127.0.0.1:5000  
        # More info: http://php.net/manual/en/function.stream-socket-client.php
        # Example of node server:
        # https://github.com/Limenius/symfony-react-sandbox/blob/master/app/Resources/node-server/server.js
        # null will default to `unix://%kernel.root_dir%/Resources/node-server/node.sock`
        server_socket_path: tcp://127.0.0.1:5000