lsw_memcache:
    session:
        pool: sessions
        auto_load: false
        prefix: "session_"
        ttl: 7200
        locking: true
        spin_lock_wait: 15000
    pools:
        # default:
        #     servers:
        #         - { host: 10.0.0.1, tcp_port: 11211, weight: 15 }
        #         - { host: 10.0.0.2, tcp_port: 11211, weight: 30 }
            # options:
            #     allow_failover: true
            #     max_failover_attempts: 20
            #     default_port: 11211
            #     chunk_size: 32768
            #     protocol: ascii
            #     hash_strategy: consistent
            #     hash_function: crc32
            #     redundancy: true
            #     session_redundancy: 2
            #     compress_threshold: 20000
            #     lock_timeout: 15
        sessions:
            servers:
                 - { host: localhost, tcp_port: 11212 }