#nelmio_cors_bundle
nelmio_cors:
    defaults:
        allow_credentials: true #
        origin_regex: false
        allow_origin: ['*']
        # allow_origin: ['http://127.0.0.1:3002'] #todo:: ['%env(CORS_ALLOW_ORIGIN)%']
        # allow_origin: ['http://opinion.com/app_dev.php'] #todo:: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        # allow_headers: ['*']
        allow_headers: ['X-Custom-Auth', 'Content-Type']
        max_age: 86400

        #allow_credentials: false
        # hosts: []
    paths:
        # '^/api/':
        #     allow_origin: ['*']
        #     allow_headers: ['X-Custom-Auth']  #['*']
        #     allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        #     max_age: 86400
        # '^/':
        #     origin_regex: true
        #     allow_origin: ['^http://localhost:[0-9]+']
        #     allow_headers: ['X-Custom-Auth']
        #     allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        #     max_age: 3600
        #     hosts: ['^api\.']