<?php

namespace OP\UserBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * FavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteRepository extends DocumentRepository
{
}