<?php

namespace OP\UserBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends DocumentRepository
{
}