<?php

namespace OP\UserBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends DocumentRepository
{
}