<?php

namespace OP\MessageBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MessageMetadataRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class MessageMetadataRepository extends DocumentRepository
{
}
