<?php

namespace OP\MessageBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository,
    OP\UserBundle\Document\User;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ResponseRepository extends DocumentRepository
{
    public function findResponsesByQuestionId($questionId){
        $qb = $this->createQueryBuilder('\OP\MessageBundle\Document\Response');
        $qb ->field("question.id")->equals($questionId)
        	->hydrate(false);


        $responses = $qb->getQuery()
        				->execute()
        				->toArray();
        return $responses;
    }
}

