<?php

namespace OP\MessageBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ThreadMetadataRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ThreadMetadataRepository extends DocumentRepository
{
}
