<?php

namespace OP\SocialBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ObjectRepository extends DocumentRepository
{
}