export * as Posts 			from './Posts'
export * as Likes 			from './Likes'
export * as Rates 			from './Rates'
export * as Shares 			from './Shares'
export * as Authors 		from './Authors'
export * as Comments 		from './Comments'
// export * as ReplyForm 		from './ReplyForm'
export * as CommentForm 	from './CommentForm'
export * as UnderComments 	from './UnderComments'