// export Head 		from './Head'
export Foot 		from './Foot'
export IntroPrev 	from './IntroPrev'
export Intro	 	from './Intro'
export StickyMenu 	from './StickyMenu'
export OptionsPrev 	from './OptionsPrev'
export Photos 		from './Photos'
export PhotosPrev 	from './PhotosPrev'
export NavLinks 	from './NavLinks'
export PlaceBox 	from './PlaceBox'
export Members 		from './Members'
export MembersPrev 	from './MembersPrev'
export StickyNavLinks 	from './StickyNavLinks'