<?php

namespace OP\MediaBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ReactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReactionRepository extends DocumentRepository
{
}