<?php

namespace OP\MediaBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends DocumentRepository
{
    private function qb()
    {
        return $this->createQueryBuilder('\OP\PostBundle\Document\Video');
    }
    
    public function findSimpleVideosById($video_id)
    {
        $qb = $this->qb();
        $qb ->field('id')->equals($video_id)            
            ->limit(1)
            ->hydrate(false);
        
        $post = $qb->getQuery()
                   ->execute()
                   ->getSingleResult();
        return $post;    
    }
}