<?php

namespace OP\PostBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * LeftCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeftCommentRepository extends DocumentRepository
{
	public function load($postId){
        $qb = $this->createQueryBuilder('\OP\PostBundle\Document\LeftComment');
            $qb->field('post.$id')->equals(new \MongoId($postId))
            ->sort('createdAt', 'DESC')
            ->hydrate(false)
            ->limit(1)
                ;
        $comment = $qb ->getQuery()->execute()->getSingleResult();
        return $comment;
    }
}