<?php

namespace OP\OpinionBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * OlikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OlikeRepository extends DocumentRepository
{
}