<?php

namespace OP\OpinionBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * OunlikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OunlikeRepository extends DocumentRepository
{
}